version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm start
  react:
    image: node:14
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/react-app
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
